import React from "react";
import Head from "next/head";
import Link from "next/link";

import { ArticleMeta } from "utils/types";
import { getBlogPosts } from "@utils/content";

interface HomePageProps {
  articles: Array<ArticleMeta>;
}

const Home = ({ articles }: HomePageProps) => {
  return (
    <div>
      <Head>
        <title>Mikey - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-2xl">Blog.</h1>
        {articles.map((article, index) => (
          <Link
            href={`/blog/${article.slug}`}
            passHref
            key={article.slug || index}
          >
            <a>{article?.title || ""}</a>
          </Link>
        ))}
      </main>
      <footer></footer>
    </div>
  );
};

export async function getStaticProps() {
  const articles = await getBlogPosts({ limit: 0 });

  return {
    props: {
      articles: articles,
    },
  };
}

export default Home;
