import React from "react";
import Head from "next/head";

const Portfolio = () => {
  return (
    <div>
      <Head>
        <title>Mikey - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {articles.map((article, index) => (
          <Link href={`/blog/${article.slug}`} key={article.slug || index}>
            <h1>{article?.title || ""}</h1>
          </Link>
        ))} */}
        About
      </main>
    </div>
  );
};

export default Portfolio;
